matcher:
  KDTreeMatcher:
   searchType: 0
   maxDist: 1
   knn: 5

outlierFilters:
  - MaxDistOutlierFilter:
     maxDist: 0.4

errorMinimizer:
  PointToPointErrorMinimizer

transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.01
      minDiffTransErr: 0.00001
      smoothLength: 5
  - CounterTransformationChecker:
      maxIterationCount: 400
  - BoundTransformationChecker:
      maxRotationNorm: 0.8
      maxTranslationNorm: 30.00

inspector:
# VTKFileInspector
 NullInspector

logger:
  NullLogger
#  FileLogger
